server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: httpbin_route
          uri: https://httpbin.org:443
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Source, spring-cloud-gateway
